version: '3.7'
services:
  nginx:
    image: nginx:1.23
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - {{cookiecutter.port}}:80
    depends_on:
      - backend
      - frontend