version: '3.8'

services:
  backend:
    build: ./services/backend
    ports:
      - 4000:4000
    volumes:
      - ./services/backend:/app
    command: uvicorn src.app.api:app --reload --host 0.0.0.0 --port 4000
    environment:
      - DATABASE_URL=postgres://taghub_user:taghub_pw@db:5432/taghub_db
  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    command: yarn vite --host 3000
  db:
    image: postgres:14
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taghub_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
volumes:
  postgres_data:
    driver: local
