// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/Accordion.vue')['default']
    Breadcrumb: typeof import('./components/Breadcrumb.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    EditorHeader: typeof import('./components/EditorHeader.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarApp: typeof import('./components/SidebarApp.vue')['default']
  }
}
