version: 2.1

executors:
  python310-docker:
    docker:
      - image: cimg/python:3.10
    resource_class: medium
  nodelts-docker:
    docker:
      - image: cimg/node:lts
    resource_class: medium

commands:
  run_build_test_backend:
    steps:
      - checkout:
          path: ~/taghub
      - run:
          name: "Install module package"
          command: |
            pip install -r requirements.txt
      - run:
          name: "Install test package"
          command: |
            pip install -r test_requirements.txt
      - run:
          name: "Test backend with coverage"
          command: |
            pytest tests
  run_build_test_frontend:
    steps:
      - checkout:
          path: ~/taghub
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test
      
jobs:
  test_backend:
    working_directory: ~/taghub/backend
    executor: python310-docker
    steps:
      - run_build_test_backend
  test_frontend:
    working_directory: ~/taghub/frontend
    executor: nodelts-docker
    steps:
      - run_build_test_frontend

workflows:
  # Name the workflow "welcome"
  main:
    # Run the welcome/run job in its own container
    jobs:
      - test_backend
      - test_frontend