version: 2.1

executors:
  python310-docker:
    docker:
      - image: cimg/python:3.10
    resource_class: medium

commands:
  run_build_test_backend:
    steps:
      - checkout
      - run:
          name: "Install module package"
          command: |
            pip install -r requirements.txt
      - run:
          name: "Install test package"
          command: |
            pip install -r test_requirements.txt
      - run:
          name: "Test backend with coverage"
          command: |
            pytest tests
      
jobs:
  test_backend:
    executor: python310-docker
    steps:
      - run_build_test_backend

workflows:
  # Name the workflow "welcome"
  main:
    # Run the welcome/run job in its own container
    jobs:
      - test_backend